Create-Component-Use-Cases
CondensationDS/Condensation-Website pull request #39
Opened 2022-02-27 17:26 UTC by CharlineLavigne

2022-02-27 19:26 UTC, AlexikM commented on components/UseCases.js
> +import imageTop from '../assets/img/user-case-privacy-phone.png';
The images shouldn't be imported inside of the component - but from the page displaying the component

2022-02-27 19:27 UTC, AlexikM commented on components/UseCases.js
> +                    alt="Use case illustration" />
Alt cannot be the same for all pictures.

2022-02-27 19:28 UTC, AlexikM requested changes
Thanks a lot Kali, please check my comments

2022-02-28 10:32 UTC, souksou commented on components/UseCases.js
> +        <div className='bg-[#EAEAEA] flex flex-col md:flex-row w-[80%] m-auto'>
Please use global variable for the styling or create a new task for theming.

2022-02-28 10:33 UTC, souksou commented on components/UseCases.js
> +            <p className='w-[60%] md:w-[40%] text-[3vw] md:text-[1.9vw] ml-10 mt-10 md:m-auto md:ml-10'>
Please use tailwind variable for the text example: 
md:text-xl

2022-03-04 22:35 UTC, AlexikM approved these changes

2022-03-04 22:35 UTC, merged